In [1]:
import pandas as pd
import numpy as np

In [2]:
deliveries = pd.read_csv(r"C:\Users\yasar\OneDrive\Desktop\IPL Analysis\Data\deliveries.csv")
matches = pd.read_csv(r"C:\Users\yasar\OneDrive\Desktop\IPL Analysis\Data\matches.csv")

Deliveries data processing

In [4]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [5]:
deliveries.isna().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [6]:
deliveries_1 = deliveries.drop(columns = ['extras_type', 'player_dismissed', 'dismissal_kind', 'fielder'], axis = 1)

In [7]:
deliveries_1.isna().sum()

match_id        0
inning          0
batting_team    0
bowling_team    0
over            0
ball            0
batter          0
bowler          0
non_striker     0
batsman_runs    0
extra_runs      0
total_runs      0
is_wicket       0
dtype: int64

In [8]:
deliveries_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   match_id      260920 non-null  int64
 1   inning        260920 non-null  int64
 2   batting_team  260920 non-null  object
 3   bowling_team  260920 non-null  object
 4   over          260920 non-null  int64
 5   ball          260920 non-null  int64
 6   batter        260920 non-null  object
 7   bowler        260920 non-null  object
 8   non_striker   260920 non-null  object
 9   batsman_runs  260920 non-null  int64
 10  extra_runs    260920 non-null  int64
 11  total_runs    260920 non-null  int64
 12  is_wicket     260920 non-null  int64
dtypes: int64(8), object(5)
memory usage: 25.9+ MB

In [22]:
deliveries_1.to_csv(r"C:\Users\yasar\OneDrive\Desktop\IPL Analysis\Cleaned_data\deliveries_cleaned.csv", index = None)

Matches data processing

In [9]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [10]:
matches_1 = matches.copy()

In [11]:
matches_1['method'].fillna('Normal', inplace = True)
matches_1['city'].fillna('Not available', inplace = True)
matches_1['result_margin'].fillna(0, inplace = True)

In [12]:
matches_1.dropna(subset = ['target_overs', 'winner'], inplace = True)

In [13]:
matches_1.isna().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
dtype: int64

In [15]:
matches_1.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Normal,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,Normal,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,Normal,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,Normal,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,Normal,BF Bowden,K Hariharan

In [16]:
matches_1 = matches_1.rename(columns = {'id':'match_id'})

In [23]:
matches_1.to_csv(r"C:\Users\yasar\OneDrive\Desktop\IPL Analysis\Cleaned_data\matches_cleaned.csv", index = None)

In [18]:
merged = pd.merge(matches_1, deliveries_1, on = 'match_id')

In [19]:
merged_clean = merged[['match_id', 'batting_team', 'bowling_team', 'batter', 'bowler', 'venue', 
        'season', 'match_type', 'batsman_runs', 'extra_runs', 'total_runs', 'is_wicket']]

In [20]:
merged_clean.head()

,match_id,batting_team,bowling_team,batter,bowler,venue,season,match_type,batsman_runs,extra_runs,total_runs,is_wicket
0,335982,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,M Chinnaswamy Stadium,2007/08,League,0,1,1,0
1,335982,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,M Chinnaswamy Stadium,2007/08,League,0,0,0,0
2,335982,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,M Chinnaswamy Stadium,2007/08,League,0,1,1,0
3,335982,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,M Chinnaswamy Stadium,2007/08,League,0,0,0,0
4,335982,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,M Chinnaswamy Stadium,2007/08,League,0,0,0,0

In [21]:
merged_clean[merged_clean['batting_team'] == "Chennai Super Kings"][['batting_team', 'batter', 
                                                                     'batsman_runs', 'venue', 
                                                                    'season', 'match_type']]

,batting_team,batter,batsman_runs,venue,season,match_type
225,Chennai Super Kings,PA Patel,0,"Punjab Cricket Association Stadium, Mohali",2007/08,League
226,Chennai Super Kings,PA Patel,0,"Punjab Cricket Association Stadium, Mohali",2007/08,League
227,Chennai Super Kings,PA Patel,1,"Punjab Cricket Association Stadium, Mohali",2007/08,League
228,Chennai Super Kings,ML Hayden,0,"Punjab Cricket Association Stadium, Mohali",2007/08,League
229,Chennai Super Kings,ML Hayden,4,"Punjab Cricket Association Stadium, Mohali",2007/08,League
...,...,...,...,...,...,...
259294,Chennai Super Kings,MS Dhoni,0,"M Chinnaswamy Stadium, Bengaluru",2024,League
259295,Chennai Super Kings,SN Thakur,0,"M Chinnaswamy Stadium, Bengaluru",2024,League
259296,Chennai Super Kings,SN Thakur,1,"M Chinnaswamy Stadium, Bengaluru",2024,League
259297,Chennai Super Kings,RA Jadeja,0,"M Chinnaswamy Stadium, Bengaluru",2024,League
259298,Chennai Super Kings,RA Jadeja,0,"M Chinnaswamy Stadium, Bengaluru",2024,League

In [ ]:
merged_clean.to_csv(r"C:\Users\yasar\OneDrive\Desktop\IPL Analysis\Cleaned_data\merged_cleaned.csv", index = None)